# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

permalink:  pretty
plugins:             [jekyll-paginate]

# Setup
title:               Davide Depau's Blog
tagline:             'Tech stories'
description:         'Experiences with tech and stuff.'
url:                 https://blog.depau.eu
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Davide Depau
  url:               https://github.com/Depau
  email:             davide@depau.eu
  instagram:         depaulicious
  github:            Depau
  poliedro:          https://poliedro-polimi.it
  polimipride:       https://polimipride.it
